#!/bin/bash -l        
#SBATCH --time=01:00:00
#SBATCH --ntasks=100
#SBATCH --mem=30g
#SBATCH --tmp=10g
#SBATCH --mail-type=ALL  
#SBATCH --mail-user=khark007@umn.edu 
cd ~/Downloads/Covid-19-LTC-facilties
module load intel 
mpirun -np 100 python main.py > result
